### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by officialmmt** [datalogix/laravel-tailwind-components#1]
How I can use this package?

**Comment by cubancodepath** [comment]
How I can use this package?

**Comment by officialmmt** [comment]
@bjvalmaseda92 Hi, if you don't get anything from developer maybe you can use => [link](https://github.com/datalogix/laravel-tailwind-components/tree/master/tests/Feature/views/form) there is some sample for using.

**Comment by ricardogobbosouza** [comment]
Hi @bjvalmaseda92 , @officialmmt 
I'm working on another project [tallkit](https://github.com/datalogix/tall-kit) that will deprecate this one .

This new library is much more comprehensive.
Components: https://github.com/datalogix/tall-kit/tree/main/src/Components

I'm currently working on the docs.
